"""
Generates a test SPSTR CSV using the actual data from the provided PDF samples.
The 7 real rows from the SPSTR PDF are included as-is (all Wasted Adspend).
Additional rows are added using the same campaign/product patterns to cover
all 4 categories: Wasted, Inefficient, Scaling Opportunity, Harvesting Opportunity.
"""

import csv
import os

COLUMNS = [
    "Product",
    "Campaign ID",
    "Ad Group ID",
    "Keyword ID",
    "Product Targeting ID",
    "Campaign Name (Informational only)",
    "Ad Group Name (Informational only)",
    "Portfolio Name (Informational only)",
    "State",
    "Campaign State (Informational only)",
    "Bid",
    "Keyword Text",
    "Match Type",
    "Product Targeting Expression",
    "Resolved Product Targeting Expression (Informational only)",
    "Customer Search Term",
    "Impressions",
    "Clicks",
    "Click-through Rate",
    "Spend",
    "Sales",
    "Orders",
    "Units",
    "Conversion Rate",
    "ACOS",
    "CPC",
    "ROAS",
]

# =========================================================================
# Actual rows from the provided SPSTR PDF (all Wasted Adspend: high clicks, 0 orders)
# Reconstructed from: SPSTR - Bulk.xlsx.pdf
# =========================================================================
REAL_SPSTR_ROWS = [
    {
        "Product": "Sponsored Products",
        "Campaign ID": "514290153054958",
        "Ad Group ID": "338763421328727",
        "Keyword ID": "281906242036075",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": '"kids golf clubs 3-5" - EX - HSV - Kids Putter Extendable Silver - Incrementum - Sherlock',
        "Ad Group Name (Informational only)": "Exact",
        "Portfolio Name (Informational only)": "03. Kids Putter - Extendable Silver - B0CKRTNMPM | B0BNJ395S1 - Go for it golf",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "2.18",
        "Keyword Text": "kids golf clubs 3-5",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "kids golf clubs 3-5",
        "Impressions": 652,
        "Clicks": 12,
        "Click-through Rate": "1.84%",
        "Spend": 26.16,
        "Sales": 0.00,
        "Orders": 0,
        "Units": 0,
        "Conversion Rate": "0.00%",
        "ACOS": "0.00%",
        "CPC": 2.18,
        "ROAS": 0.00,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "286611797534744",
        "Ad Group ID": "447190817537962",
        "Keyword ID": "480932444716050",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": '"kids golf clubs" - 10K HSV - EX - B0FYS4MSBS - Junior Golf Club Set - Incrementum',
        "Ad Group Name (Informational only)": "Exact",
        "Portfolio Name (Informational only)": "28. November - Junior Golf Club Set",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "1.21",
        "Keyword Text": "kids golf clubs",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "kids golf clubs",
        "Impressions": 1222,
        "Clicks": 20,
        "Click-through Rate": "1.64%",
        "Spend": 22.28,
        "Sales": 0.00,
        "Orders": 0,
        "Units": 0,
        "Conversion Rate": "0.00%",
        "ACOS": "0.00%",
        "CPC": 1.11,
        "ROAS": 0.00,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "556268903645598",
        "Ad Group ID": "307784767455836",
        "Keyword ID": "335287550986705",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "200 LSV - PH - Competitor Brand - B0CZFV5WHW - Equalizer Golf Card - Incrementum",
        "Ad Group Name (Informational only)": "200 LSV - PH - Competitor Brand - B0CZFV5WHW - Equalizer Golf Card - Incrementum",
        "Portfolio Name (Informational only)": "14. Equalizer On-Coarse Golf Card Game - B0CZFV5WHW - Go for it Golf",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "1.59",
        "Keyword Text": "play9 card game",
        "Match Type": "Phrase",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "play9 card game",
        "Impressions": 1534,
        "Clicks": 13,
        "Click-through Rate": "0.85%",
        "Spend": 24.67,
        "Sales": 0.00,
        "Orders": 0,
        "Units": 0,
        "Conversion Rate": "0.00%",
        "ACOS": "0.00%",
        "CPC": 1.90,
        "ROAS": 0.00,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "507042941633893",
        "Ad Group ID": "451442274269531",
        "Keyword ID": "474242458202934",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "2K HSV - BR - B0BG3GCD47 - Ferrofluid - SKC (ferrofluid) - Incrementum",
        "Ad Group Name (Informational only)": "Broad",
        "Portfolio Name (Informational only)": "01. Ferrofluid - Pure Source + Stem Source",
        "State": "paused",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.62",
        "Keyword Text": "ferrofluid",
        "Match Type": "Broad",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "ferrofluid",
        "Impressions": 537,
        "Clicks": 12,
        "Click-through Rate": "2.23%",
        "Spend": 7.31,
        "Sales": 0.00,
        "Orders": 0,
        "Units": 0,
        "Conversion Rate": "0.00%",
        "ACOS": "0.00%",
        "CPC": 0.61,
        "ROAS": 0.00,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "530588307699315",
        "Ad Group ID": "479142982150977",
        "Keyword ID": "281807388574843",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "MSV (800) - EX - MKW - B0FYS4MSBS - Junior Golf Club Set - Incrementum",
        "Ad Group Name (Informational only)": "Ad Group - 12/4/2025 19:20:15.025",
        "Portfolio Name (Informational only)": "28. November - Junior Golf Club Set",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "1.42",
        "Keyword Text": "kids left handed golf clubs",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "kids left handed golf clubs",
        "Impressions": 305,
        "Clicks": 12,
        "Click-through Rate": "3.93%",
        "Spend": 15.67,
        "Sales": 0.00,
        "Orders": 0,
        "Units": 0,
        "Conversion Rate": "0.00%",
        "ACOS": "0.00%",
        "CPC": 1.31,
        "ROAS": 0.00,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "461832373850853",
        "Ad Group ID": "536588873717814",
        "Keyword ID": "353352541715631",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "SP - KW - PH - Ferrofluid - B0BG3GCD47 - 5 MSV KWs - Incrementum - Sherlock 1",
        "Ad Group Name (Informational only)": "Phrase",
        "Portfolio Name (Informational only)": "01. Ferrofluid - Pure Source + Stem Source",
        "State": "paused",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.92",
        "Keyword Text": "ferrofluid visualizer",
        "Match Type": "Phrase",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "ferrofluid visualizer",
        "Impressions": 1805,
        "Clicks": 17,
        "Click-through Rate": "0.94%",
        "Spend": 17.85,
        "Sales": 0.00,
        "Orders": 0,
        "Units": 0,
        "Conversion Rate": "0.00%",
        "ACOS": "0.00%",
        "CPC": 1.05,
        "ROAS": 0.00,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "393518651546755",
        "Ad Group ID": "557880985911089",
        "Keyword ID": "358098147217317",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "SP - Low Bid Auto - B0FXY4G65C - Ferrofluid - Close 1",
        "Ad Group Name (Informational only)": "Ad Group - 11/13/2025 20:03:53.168",
        "Portfolio Name (Informational only)": "25. B0FXY4G65C - Ferrofluid",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.35",
        "Keyword Text": "",
        "Match Type": "close-match",
        "Product Targeting Expression": "close-match",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "ferrofluid",
        "Impressions": 1071,
        "Clicks": 17,
        "Click-through Rate": "1.59%",
        "Spend": 8.78,
        "Sales": 0.00,
        "Orders": 0,
        "Units": 0,
        "Conversion Rate": "0.00%",
        "ACOS": "0.00%",
        "CPC": 0.52,
        "ROAS": 0.00,
    },
]

# =========================================================================
# Additional rows using the same real campaign patterns to cover the
# other 3 categories (Inefficient, Scaling, Harvesting)
# =========================================================================
ADDITIONAL_ROWS = [
    # ---- INEFFICIENT ADSPEND: High ACOS, Orders > 0 ----
    {
        "Product": "Sponsored Products",
        "Campaign ID": "514290153054958",
        "Ad Group ID": "338763421328727",
        "Keyword ID": "281906242036076",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": '"kids golf clubs 3-5" - EX - HSV - Kids Putter Extendable Silver - Incrementum - Sherlock',
        "Ad Group Name (Informational only)": "Exact",
        "Portfolio Name (Informational only)": "03. Kids Putter - Extendable Silver - B0CKRTNMPM | B0BNJ395S1 - Go for it golf",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "2.50",
        "Keyword Text": "kids golf set age 3",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "kids golf set age 3",
        "Impressions": 3200,
        "Clicks": 45,
        "Click-through Rate": "1.41%",
        "Spend": 98.10,
        "Sales": 149.97,
        "Orders": 3,
        "Units": 3,
        "Conversion Rate": "6.67%",
        "ACOS": "65.41%",
        "CPC": 2.18,
        "ROAS": 1.53,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "286611797534744",
        "Ad Group ID": "447190817537962",
        "Keyword ID": "480932444716051",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": '"kids golf clubs" - 10K HSV - EX - B0FYS4MSBS - Junior Golf Club Set - Incrementum',
        "Ad Group Name (Informational only)": "Exact",
        "Portfolio Name (Informational only)": "28. November - Junior Golf Club Set",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "1.50",
        "Keyword Text": "junior golf club set",
        "Match Type": "Broad",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "junior golf club set for beginners",
        "Impressions": 5400,
        "Clicks": 72,
        "Click-through Rate": "1.33%",
        "Spend": 86.40,
        "Sales": 189.99,
        "Orders": 3,
        "Units": 3,
        "Conversion Rate": "4.17%",
        "ACOS": "45.47%",
        "CPC": 1.20,
        "ROAS": 2.20,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "507042941633893",
        "Ad Group ID": "451442274269531",
        "Keyword ID": "474242458202935",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "2K HSV - BR - B0BG3GCD47 - Ferrofluid - SKC (ferrofluid) - Incrementum",
        "Ad Group Name (Informational only)": "Broad",
        "Portfolio Name (Informational only)": "01. Ferrofluid - Pure Source + Stem Source",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.80",
        "Keyword Text": "ferrofluid",
        "Match Type": "Broad",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "ferrofluid magnetic display bottle",
        "Impressions": 4100,
        "Clicks": 55,
        "Click-through Rate": "1.34%",
        "Spend": 44.00,
        "Sales": 59.99,
        "Orders": 2,
        "Units": 2,
        "Conversion Rate": "3.64%",
        "ACOS": "73.34%",
        "CPC": 0.80,
        "ROAS": 1.36,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "556268903645598",
        "Ad Group ID": "307784767455836",
        "Keyword ID": "335287550986706",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "200 LSV - PH - Competitor Brand - B0CZFV5WHW - Equalizer Golf Card - Incrementum",
        "Ad Group Name (Informational only)": "200 LSV - PH - Competitor Brand - B0CZFV5WHW - Equalizer Golf Card - Incrementum",
        "Portfolio Name (Informational only)": "14. Equalizer On-Coarse Golf Card Game - B0CZFV5WHW - Go for it Golf",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "1.75",
        "Keyword Text": "golf card game",
        "Match Type": "Phrase",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "golf card game for adults",
        "Impressions": 2800,
        "Clicks": 38,
        "Click-through Rate": "1.36%",
        "Spend": 66.50,
        "Sales": 119.96,
        "Orders": 4,
        "Units": 4,
        "Conversion Rate": "10.53%",
        "ACOS": "55.44%",
        "CPC": 1.75,
        "ROAS": 1.80,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "530588307699315",
        "Ad Group ID": "479142982150977",
        "Keyword ID": "281807388574844",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "MSV (800) - EX - MKW - B0FYS4MSBS - Junior Golf Club Set - Incrementum",
        "Ad Group Name (Informational only)": "Ad Group - 12/4/2025 19:20:15.025",
        "Portfolio Name (Informational only)": "28. November - Junior Golf Club Set",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "1.80",
        "Keyword Text": "golf clubs for 5 year old",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "golf clubs for 5 year old",
        "Impressions": 1900,
        "Clicks": 30,
        "Click-through Rate": "1.58%",
        "Spend": 48.00,
        "Sales": 79.99,
        "Orders": 1,
        "Units": 1,
        "Conversion Rate": "3.33%",
        "ACOS": "60.00%",
        "CPC": 1.60,
        "ROAS": 1.67,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "461832373850853",
        "Ad Group ID": "536588873717814",
        "Keyword ID": "353352541715632",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "SP - KW - PH - Ferrofluid - B0BG3GCD47 - 5 MSV KWs - Incrementum - Sherlock 1",
        "Ad Group Name (Informational only)": "Phrase",
        "Portfolio Name (Informational only)": "01. Ferrofluid - Pure Source + Stem Source",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "1.00",
        "Keyword Text": "magnetic ferrofluid toy",
        "Match Type": "Phrase",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "magnetic ferrofluid display toy for desk",
        "Impressions": 6200,
        "Clicks": 85,
        "Click-through Rate": "1.37%",
        "Spend": 76.50,
        "Sales": 179.97,
        "Orders": 6,
        "Units": 7,
        "Conversion Rate": "7.06%",
        "ACOS": "42.51%",
        "CPC": 0.90,
        "ROAS": 2.35,
    },

    # ---- SCALING OPPORTUNITY: Exact match, good CVR, low clicks ----
    {
        "Product": "Sponsored Products",
        "Campaign ID": "514290153054958",
        "Ad Group ID": "338763421328727",
        "Keyword ID": "281906242036077",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": '"kids golf clubs 3-5" - EX - HSV - Kids Putter Extendable Silver - Incrementum - Sherlock',
        "Ad Group Name (Informational only)": "Exact",
        "Portfolio Name (Informational only)": "03. Kids Putter - Extendable Silver - B0CKRTNMPM | B0BNJ395S1 - Go for it golf",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "2.00",
        "Keyword Text": "toddler golf putter",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "toddler golf putter",
        "Impressions": 180,
        "Clicks": 5,
        "Click-through Rate": "2.78%",
        "Spend": 9.50,
        "Sales": 49.99,
        "Orders": 2,
        "Units": 2,
        "Conversion Rate": "40.00%",
        "ACOS": "19.00%",
        "CPC": 1.90,
        "ROAS": 5.26,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "286611797534744",
        "Ad Group ID": "447190817537962",
        "Keyword ID": "480932444716052",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": '"kids golf clubs" - 10K HSV - EX - B0FYS4MSBS - Junior Golf Club Set - Incrementum',
        "Ad Group Name (Informational only)": "Exact",
        "Portfolio Name (Informational only)": "28. November - Junior Golf Club Set",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "1.30",
        "Keyword Text": "kids golf club set with bag",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "kids golf club set with bag",
        "Impressions": 95,
        "Clicks": 4,
        "Click-through Rate": "4.21%",
        "Spend": 5.20,
        "Sales": 69.99,
        "Orders": 1,
        "Units": 1,
        "Conversion Rate": "25.00%",
        "ACOS": "7.43%",
        "CPC": 1.30,
        "ROAS": 13.46,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "507042941633893",
        "Ad Group ID": "451442274269531",
        "Keyword ID": "474242458202936",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "2K HSV - BR - B0BG3GCD47 - Ferrofluid - SKC (ferrofluid) - Incrementum",
        "Ad Group Name (Informational only)": "Broad",
        "Portfolio Name (Informational only)": "01. Ferrofluid - Pure Source + Stem Source",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.75",
        "Keyword Text": "ferrofluid bottle",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "ferrofluid bottle",
        "Impressions": 210,
        "Clicks": 7,
        "Click-through Rate": "3.33%",
        "Spend": 5.25,
        "Sales": 29.99,
        "Orders": 1,
        "Units": 1,
        "Conversion Rate": "14.29%",
        "ACOS": "17.51%",
        "CPC": 0.75,
        "ROAS": 5.71,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "556268903645598",
        "Ad Group ID": "307784767455836",
        "Keyword ID": "335287550986707",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "200 LSV - PH - Competitor Brand - B0CZFV5WHW - Equalizer Golf Card - Incrementum",
        "Ad Group Name (Informational only)": "200 LSV - PH - Competitor Brand - B0CZFV5WHW - Equalizer Golf Card - Incrementum",
        "Portfolio Name (Informational only)": "14. Equalizer On-Coarse Golf Card Game - B0CZFV5WHW - Go for it Golf",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "1.50",
        "Keyword Text": "golf scorecard game",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "golf scorecard game",
        "Impressions": 145,
        "Clicks": 6,
        "Click-through Rate": "4.14%",
        "Spend": 9.00,
        "Sales": 59.98,
        "Orders": 2,
        "Units": 2,
        "Conversion Rate": "33.33%",
        "ACOS": "15.01%",
        "CPC": 1.50,
        "ROAS": 6.66,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "530588307699315",
        "Ad Group ID": "479142982150977",
        "Keyword ID": "281807388574845",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "MSV (800) - EX - MKW - B0FYS4MSBS - Junior Golf Club Set - Incrementum",
        "Ad Group Name (Informational only)": "Ad Group - 12/4/2025 19:20:15.025",
        "Portfolio Name (Informational only)": "28. November - Junior Golf Club Set",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "1.60",
        "Keyword Text": "left handed toddler golf clubs",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "left handed toddler golf clubs",
        "Impressions": 120,
        "Clicks": 3,
        "Click-through Rate": "2.50%",
        "Spend": 4.80,
        "Sales": 79.99,
        "Orders": 1,
        "Units": 1,
        "Conversion Rate": "33.33%",
        "ACOS": "6.00%",
        "CPC": 1.60,
        "ROAS": 16.66,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "461832373850853",
        "Ad Group ID": "536588873717814",
        "Keyword ID": "353352541715633",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "SP - KW - PH - Ferrofluid - B0BG3GCD47 - 5 MSV KWs - Incrementum - Sherlock 1",
        "Ad Group Name (Informational only)": "Phrase",
        "Portfolio Name (Informational only)": "01. Ferrofluid - Pure Source + Stem Source",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.85",
        "Keyword Text": "ferrofluid science kit",
        "Match Type": "Exact",
        "Product Targeting Expression": "",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "ferrofluid science kit",
        "Impressions": 88,
        "Clicks": 3,
        "Click-through Rate": "3.41%",
        "Spend": 2.55,
        "Sales": 29.99,
        "Orders": 1,
        "Units": 1,
        "Conversion Rate": "33.33%",
        "ACOS": "8.50%",
        "CPC": 0.85,
        "ROAS": 11.76,
    },

    # ---- HARVESTING OPPORTUNITY: Not targeted (auto match), Orders > 2 ----
    {
        "Product": "Sponsored Products",
        "Campaign ID": "393518651546755",
        "Ad Group ID": "557880985911089",
        "Keyword ID": "358098147217318",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "SP - Low Bid Auto - B0FXY4G65C - Ferrofluid - Close 1",
        "Ad Group Name (Informational only)": "Ad Group - 11/13/2025 20:03:53.168",
        "Portfolio Name (Informational only)": "25. B0FXY4G65C - Ferrofluid",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.35",
        "Keyword Text": "",
        "Match Type": "close-match",
        "Product Targeting Expression": "close-match",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "cool desk toys for men",
        "Impressions": 3500,
        "Clicks": 42,
        "Click-through Rate": "1.20%",
        "Spend": 21.00,
        "Sales": 179.97,
        "Orders": 6,
        "Units": 7,
        "Conversion Rate": "14.29%",
        "ACOS": "11.67%",
        "CPC": 0.50,
        "ROAS": 8.57,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "393518651546755",
        "Ad Group ID": "557880985911089",
        "Keyword ID": "358098147217319",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "SP - Low Bid Auto - B0FXY4G65C - Ferrofluid - Close 1",
        "Ad Group Name (Informational only)": "Ad Group - 11/13/2025 20:03:53.168",
        "Portfolio Name (Informational only)": "25. B0FXY4G65C - Ferrofluid",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.35",
        "Keyword Text": "",
        "Match Type": "loose-match",
        "Product Targeting Expression": "loose-match",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "magnetic desk toy fidget",
        "Impressions": 2800,
        "Clicks": 35,
        "Click-through Rate": "1.25%",
        "Spend": 15.75,
        "Sales": 119.96,
        "Orders": 4,
        "Units": 4,
        "Conversion Rate": "11.43%",
        "ACOS": "13.13%",
        "CPC": 0.45,
        "ROAS": 7.62,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "393518651546755",
        "Ad Group ID": "557880985911089",
        "Keyword ID": "358098147217320",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "SP - Low Bid Auto - B0FXY4G65C - Ferrofluid - Close 1",
        "Ad Group Name (Informational only)": "Ad Group - 11/13/2025 20:03:53.168",
        "Portfolio Name (Informational only)": "25. B0FXY4G65C - Ferrofluid",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.35",
        "Keyword Text": "",
        "Match Type": "close-match",
        "Product Targeting Expression": "close-match",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "science experiment kits for kids",
        "Impressions": 5200,
        "Clicks": 68,
        "Click-through Rate": "1.31%",
        "Spend": 34.00,
        "Sales": 269.95,
        "Orders": 9,
        "Units": 10,
        "Conversion Rate": "13.24%",
        "ACOS": "12.59%",
        "CPC": 0.50,
        "ROAS": 7.94,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "393518651546755",
        "Ad Group ID": "557880985911089",
        "Keyword ID": "358098147217321",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "SP - Low Bid Auto - B0FXY4G65C - Ferrofluid - Close 1",
        "Ad Group Name (Informational only)": "Ad Group - 11/13/2025 20:03:53.168",
        "Portfolio Name (Informational only)": "25. B0FXY4G65C - Ferrofluid",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.35",
        "Keyword Text": "",
        "Match Type": "substitutes",
        "Product Targeting Expression": "substitutes",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "liquid magnet toy",
        "Impressions": 1800,
        "Clicks": 25,
        "Click-through Rate": "1.39%",
        "Spend": 12.50,
        "Sales": 89.97,
        "Orders": 3,
        "Units": 3,
        "Conversion Rate": "12.00%",
        "ACOS": "13.89%",
        "CPC": 0.50,
        "ROAS": 7.20,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "393518651546755",
        "Ad Group ID": "557880985911089",
        "Keyword ID": "358098147217322",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "SP - Low Bid Auto - B0FXY4G65C - Ferrofluid - Close 1",
        "Ad Group Name (Informational only)": "Ad Group - 11/13/2025 20:03:53.168",
        "Portfolio Name (Informational only)": "25. B0FXY4G65C - Ferrofluid",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.35",
        "Keyword Text": "",
        "Match Type": "complements",
        "Product Targeting Expression": "complements",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "stem toys for boys age 8-12",
        "Impressions": 4100,
        "Clicks": 52,
        "Click-through Rate": "1.27%",
        "Spend": 26.00,
        "Sales": 239.96,
        "Orders": 8,
        "Units": 9,
        "Conversion Rate": "15.38%",
        "ACOS": "10.84%",
        "CPC": 0.50,
        "ROAS": 9.23,
    },
    {
        "Product": "Sponsored Products",
        "Campaign ID": "393518651546755",
        "Ad Group ID": "557880985911089",
        "Keyword ID": "358098147217323",
        "Product Targeting ID": "",
        "Campaign Name (Informational only)": "SP - Low Bid Auto - B0FXY4G65C - Ferrofluid - Close 1",
        "Ad Group Name (Informational only)": "Ad Group - 11/13/2025 20:03:53.168",
        "Portfolio Name (Informational only)": "25. B0FXY4G65C - Ferrofluid",
        "State": "enabled",
        "Campaign State (Informational only)": "enabled",
        "Bid": "0.35",
        "Keyword Text": "",
        "Match Type": "loose-match",
        "Product Targeting Expression": "loose-match",
        "Resolved Product Targeting Expression (Informational only)": "",
        "Customer Search Term": "unique gift for science lovers",
        "Impressions": 3200,
        "Clicks": 40,
        "Click-through Rate": "1.25%",
        "Spend": 20.00,
        "Sales": 149.97,
        "Orders": 5,
        "Units": 5,
        "Conversion Rate": "12.50%",
        "ACOS": "13.34%",
        "CPC": 0.50,
        "ROAS": 7.50,
    },
]


def generate(output_path: str = None) -> str:
    if output_path is None:
        output_path = os.path.join(os.path.dirname(__file__), "dummy_spstr.csv")

    all_rows = REAL_SPSTR_ROWS + ADDITIONAL_ROWS

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=COLUMNS)
        writer.writeheader()
        writer.writerows(all_rows)

    print(f"Generated {len(all_rows)} rows -> {output_path}")
    print(f"  Real SPSTR rows (Wasted Adspend): {len(REAL_SPSTR_ROWS)}")
    print(f"  Additional Inefficient Adspend:    6")
    print(f"  Additional Scaling Opportunity:     6")
    print(f"  Additional Harvesting Opportunity:  6")
    return output_path


if __name__ == "__main__":
    generate()
